version: '3.8'
# Services
services:

  jsonserver:                    # <<— AÇÍ, DINS DE "services:"
      image: node:20-alpine
      container_name: jsonserver
      working_dir: /app
      command: sh -c "npm i -g json-server && json-server --watch /data/products.json --host 0.0.0.0 --port 3000"
      volumes:
        - ./data:/data
      ports:
        - "3000:3000"
      restart: unless-stopped
      networks:
        - default

  jsonserver2:
      image: node:20-alpine
      container_name: jsonserver2
      working_dir: /app
      command: sh -c "npm i -g json-server && json-server --watch /data/users.json --host 0.0.0.0 --port 3001"
      volumes:
        - ./data:/data
      ports:
        - "3001:3001"
      restart: unless-stopped
      networks:
        - default

  nginx:
    image: nginx:1.23
    container_name: webserver-projecte
    ports:
      - 80:80
    volumes:
      - .:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:      # <--- AFEGEIX AIXÒ
      - default    # <--- AFEGEIX AIXÒ

  php:
    build: ./.docker/php/
    working_dir: /var/www/php
    container_name: php-projecte
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - .:/var/www/php
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:      # <--- AFEGEIX AIXÒ
      - default    # <--- AFEGEIX AIXÒ

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: pruebadb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
volumes:
  persistent:

    null

 

